<script>
function myFunction() {
  alert("Welcome To AlexxiOS | App Is Still Signed🟢");
}
</script>
<br>
<br>
<br>





<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.fa {
  padding: 20px;
  font-size: 30px;
  width: 30px;
  text-align: center;
  text-decoration: none;
  margin: 5px 2px;
  border-radius: 50%;
}

.fa:hover {
    opacity: 0.7;
}



.fa-telegram {
  background: #0088cc;
  color: white;
}
